import SwiftUI

struct GeneratedInsightDetailView: View {
    @Environment(\.presentationMode) var presentationMode
    let insightTitle: String
    let domainName: String
    let riskPercent: Int
    let icon: String
    let color: Color
    @EnvironmentObject var languageManager: LanguageManager
    
    var body: some View {
        ZStack {
            Color.appBackground.ignoresSafeArea()
            
            ScrollView(showsIndicators: false) {
                VStack(spacing: 24) {
                    // MARK: - Header Graphic
                    ZStack {
                        Circle()
                            .fill(color.opacity(0.1))
                            .frame(width: 120, height: 120)
                        
                        Circle()
                            .stroke(color.opacity(0.3), lineWidth: 2)
                            .frame(width: 140, height: 140)
                        
                        Image(systemName: icon)
                            .font(.system(size: 50, weight: .bold))
                            .foregroundColor(color)
                    }
                    .padding(.top, 40)
                    
                    // MARK: - Title
                    Text(insightTitle)
                        .font(.title2)
                        .fontWeight(.bold)
                        .foregroundColor(.appText)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal, 24)
                    
                    // MARK: - AI Context Card
                    VStack(alignment: .leading, spacing: 16) {
                        HStack(spacing: 8) {
                            Image(systemName: "sparkles")
                                .foregroundColor(.purple)
                            Text("AI Analysis Context")
                                .font(.headline)
                                .foregroundColor(.appText)
                        }
                        
                        Text("This insight was generated by our deep learning models analyzing recent changes in your \(domainName.lowercased()) health profile, including genetic markers and lifestyle tracking.")
                            .font(.subheadline)
                            .foregroundColor(.appSecondaryText)
                            .lineSpacing(4)
                    }
                    .padding(20)
                    .background(Color.appSecondaryBackground)
                    .cornerRadius(16)
                    .padding(.horizontal, 20)
                    
                    // MARK: - What to do next
                    VStack(alignment: .leading, spacing: 16) {
                        Text("Recommended Next Steps")
                            .font(.headline)
                            .foregroundColor(.appText)
                            .padding(.horizontal, 24)
                        
                        VStack(spacing: 12) {
                            AIActionRow(icon: "eye.fill", color: .blue, text: "See your detailed \(domainName) assessment")
                            AIActionRow(icon: "brain.head.profile", color: .orange, text: "Understand your personal risk profile")
                            AIActionRow(icon: "lightbulb.fill", color: .green, text: "Review the AI generated key findings")
                        }
                        .padding(.horizontal, 20)
                    }
                    
                    Spacer(minLength: 50)
                }
            }
        }
        .navigationTitle("AI Insight Details")
        .navigationBarTitleDisplayMode(.inline)
    }
}

struct AIActionRow: View {
    let icon: String
    let color: Color
    let text: String
    
    var body: some View {
        HStack(spacing: 16) {
            ZStack {
                Circle()
                    .fill(color.opacity(0.15))
                    .frame(width: 44, height: 44)
                
                Image(systemName: icon)
                    .font(.system(size: 20))
                    .foregroundColor(color)
            }
            
            Text(text)
                .font(.subheadline)
                .fontWeight(.medium)
                .foregroundColor(.appText)
            
            Spacer()
        }
        .padding()
        .background(Color.appSecondaryBackground)
        .cornerRadius(16)
    }
}

#Preview {
    GeneratedInsightDetailView(
        insightTitle: "Our AI detected subtle changes in your Cardiovascular risk factors. See recommendations.",
        domainName: "Cardiovascular",
        riskPercent: 45,
        icon: "heart.fill",
        color: .red
    )
    .environmentObject(LanguageManager())
}
