import SwiftUI

class LanguageManager: ObservableObject {
    @AppStorage("selectedLanguage") var selectedLanguage: String = "English"
    
    // Simple dictionary for demonstration purposes
    private let translations: [String: [String: String]] = [
        "English": [
            "GenCare Assist": "GenCare Assist",
            "Home": "Home",
            "Insights": "Insights",
            "History": "History",
            "Profile": "Profile",
            "Overall Health Score": "Overall Health Score",
            "Your current health score is based on your risk factors and lifestyle data.": "Your current health score is based on your risk factors and lifestyle data.",
            "View Details": "View Details",
            "Top Risk Areas": "Top Risk Areas",
            "Recent Insights": "Recent Insights",
            "Account & Settings": "Account & Settings",
            "Health Management": "Health Management",
            "My Health Data": "My Health Data",
            "Edit Health Info": "Edit Health Info",
            "Security & Settings": "Security & Settings",
            "Help & Support": "Help & Support",
            "Session": "Session",
            "Sign Out": "Sign Out",
            "Welcome back,": "Welcome back,",
            "Overall Risk Score": "Overall Risk Score",
            "Your current risk score is based on your health factors and lifestyle data.": "Your current risk score is based on your health factors and lifestyle data.",
            "No risk data available.": "No risk data available.",
            "No recent insights available.": "No recent insights available.",
            "health analysis complete": "health analysis complete",
            "Analysis complete": "Analysis complete",
            "Recent Assessments": "Recent Assessments",
            "Reports": "Reports",
            "Personal Health Report": "Personal Health Report",
            "Tap to view details": "Tap to view details",
            "Past Insights": "Past Insights",
            "Review previous alerts": "Review previous alerts",
            "OVERALL RISK": "OVERALL RISK",
            "Based on your genetic profile, lifestyle, and family history.": "Based on your genetic profile, lifestyle, and family history.",
            "Understand your risk": "Understand your risk",
            "Key Contributors (Family Influence)": "Key Contributors (Family Influence)",
            "Susceptibilities": "Susceptibilities",
            "Recommended Actions": "Recommended Actions"
        ],
        "Spanish": [
            "GenCare Assist": "GenCare Asistente",
            "Home": "Inicio",
            "Insights": "Perspectivas",
            "History": "Historial",
            "Profile": "Perfil",
            "Overall Health Score": "Puntuación General de Salud",
            "Your current health score is based on your risk factors and lifestyle data.": "Su puntuación de salud actual se basa en sus factores de riesgo y datos de estilo de vida.",
            "View Details": "Ver Detalles",
            "Top Risk Areas": "Áreas de Riesgo Principal",
            "Recent Insights": "Perspectivas Recientes",
            "Account & Settings": "Cuenta y Configuración",
            "Health Management": "Gestión de Salud",
            "My Health Data": "Mis Datos de Salud",
            "Edit Health Info": "Editar Info de Salud",
            "Security & Settings": "Seguridad y Configuración",
            "Help & Support": "Ayuda y Soporte",
            "Session": "Sesión",
            "Sign Out": "Cerrar Sesión",
            "Welcome back,": "Bienvenido de nuevo,",
            "Overall Risk Score": "Puntuación General de Riesgo",
            "Your current risk score is based on your health factors and lifestyle data.": "Su puntuación de riesgo actual se basa en sus factores de salud y datos de estilo de vida.",
            "No risk data available.": "No hay datos de riesgo disponibles.",
            "No recent insights available.": "No hay perspectivas recientes disponibles.",
            "health analysis complete": "análisis de salud completo",
            "Analysis complete": "Análisis completo",
            "Recent Assessments": "Evaluaciones Recientes",
            "Reports": "Informes",
            "Personal Health Report": "Informe de Salud Personal",
            "Tap to view details": "Toque para ver detalles",
            "Past Insights": "Perspectivas Pasadas",
            "Review previous alerts": "Revisar alertas anteriores",
            "OVERALL RISK": "RIESGO GENERAL",
            "Based on your genetic profile, lifestyle, and family history.": "Basado en su perfil genético, estilo de vida y antecedentes familiares.",
            "Understand your risk": "Entienda su riesgo",
            "Key Contributors (Family Influence)": "Principales Contribuyentes (Influencia Familiar)",
            "Susceptibilities": "Susceptibilidades",
            "Recommended Actions": "Acciones Recomendadas"
        ],
        "French": [
            "GenCare Assist": "GenCare Assistance",
            "Home": "Accueil",
            "Insights": "Aperçus",
            "History": "Historique",
            "Profile": "Profil",
            "Overall Health Score": "Score de Santé Global",
            "Your current health score is based on your risk factors and lifestyle data.": "Votre score de santé actuel est basé sur vos facteurs de risque et vos données de mode de vie.",
            "View Details": "Voir les Détails",
            "Top Risk Areas": "Principaux Risques",
            "Recent Insights": "Aperçus Récents",
            "Account & Settings": "Compte et Paramètres",
            "Health Management": "Gestion de la Santé",
            "My Health Data": "Mes Données Santé",
            "Edit Health Info": "Modifier Info Santé",
            "Security & Settings": "Sécurité et Paramètres",
            "Help & Support": "Aide et Support",
            "Session": "Session",
            "Sign Out": "Se Déconnecter",
            "Welcome back,": "Bienvenue de retour,",
            "Overall Risk Score": "Score de Risque Global",
            "Your current risk score is based on your health factors and lifestyle data.": "Votre score de risque actuel est basé sur vos facteurs de santé et vos données de mode de vie.",
            "No risk data available.": "Aucune donnée de risque disponible.",
            "No recent insights available.": "Aucun aperçu récent disponible.",
            "health analysis complete": "analyse de santé terminée",
            "Analysis complete": "Analyse terminée",
            "Recent Assessments": "Évaluations Récentes",
            "Reports": "Rapports",
            "Personal Health Report": "Rapport de Santé Personnel",
            "Tap to view details": "Appuyez pour voir les détails",
            "Past Insights": "Aperçus Passés",
            "Review previous alerts": "Examiner les alertes précédentes",
            "OVERALL RISK": "RISQUE GLOBAL",
            "Based on your genetic profile, lifestyle, and family history.": "Basé sur votre profil génétique, votre mode de vie et vos antécédents familiaux.",
            "Understand your risk": "Comprendre votre risque",
            "Key Contributors (Family Influence)": "Principaux Contributeurs (Influence Familiale)",
            "Susceptibilities": "Susceptibilités",
            "Recommended Actions": "Actions Recommandées"
        ],
         "Hindi": [
            "GenCare Assist": "GenCare सहायता",
            "Home": "होम",
            "Insights": "अंतर्दृष्टि",
            "History": "इतिहास",
            "Profile": "प्रोफ़ाइल",
            "Overall Health Score": "समग्र स्वास्थ्य स्कोर",
            "Your current health score is based on your risk factors and lifestyle data.": "आपका वर्तमान स्वास्थ्य स्कोर आपके जोखिम कारकों और जीवनशैली डेटा पर आधारित है।",
            "View Details": "विवरण देखें",
            "Top Risk Areas": "शीर्ष जोखिम क्षेत्र",
            "Recent Insights": "हालिया अंतर्दृष्टि",
            "Account & Settings": "खाता और सेटिंग्स",
            "Health Management": "स्वास्थ्य प्रबंधन",
            "My Health Data": "मेरा स्वास्थ्य डेटा",
            "Edit Health Info": "स्वास्थ्य जानकारी संपादित करें",
            "Security & Settings": "सुरक्षा और सेटिंग्स",
            "Help & Support": "मदद और समर्थन",
            "Session": "सत्र",
            "Sign Out": "साइन आउट करें",
            "Welcome back,": "वापसी पर स्वागत है,",
            "Overall Risk Score": "समग्र जोखिम स्कोर",
            "Your current risk score is based on your health factors and lifestyle data.": "आपका वर्तमान जोखिम स्कोर आपके स्वास्थ्य कारकों और जीवनशैली डेटा पर आधारित है।",
            "No risk data available.": "कोई जोखिम डेटा उपलब्ध नहीं है।",
            "No recent insights available.": "कोई हालिया अंतर्दृष्टि उपलब्ध नहीं है।",
            "health analysis complete": "स्वास्थ्य विश्लेषण पूरा हुआ",
            "Analysis complete": "विश्लेषण पूरा हुआ",
            "Recent Assessments": "हालिया आकलन",
            "Reports": "रिपॉर्ट्स",
            "Personal Health Report": "व्यक्तिगत स्वास्थ्य रिपोर्ट",
            "Tap to view details": "विवरण देखने के लिए टैप करें",
            "Past Insights": "पिछली अंतर्दृष्टि",
            "Review previous alerts": "पिछले अलर्ट की समीक्षा करें",
            "OVERALL RISK": "समग्र जोखिम",
            "Based on your genetic profile, lifestyle, and family history.": "आपके आनुवंशिक प्रोफ़ाइल, जीवनशैली और पारिवारिक इतिहास पर आधारित।",
            "Understand your risk": "अपना जोखिम समझें",
            "Key Contributors (Family Influence)": "प्रमुख योगदानकर्ता (पारिवारिक प्रभाव)",
            "Susceptibilities": "संवेदनशीलता",
            "Recommended Actions": "अनुशंसित कार्रवाइयां"
        ]
        // Add other languages as needed...
    ]
    
    func setLanguage(_ language: String) {
        objectWillChange.send()
        selectedLanguage = language
    }
    
    func localizedString(_ key: String) -> String {
        // Fallback to English if language or key is missing
        if let languageDict = translations[selectedLanguage], let value = languageDict[key] {
            return value
        }
        return key
    }
}